[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ['Denial', 'Drainer']


[rpc_endpoints]
goerli = "https://eth-goerli.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
# See more config options https://github.com/foundry-rs/foundry/tree/master/config